In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

# Tensor Initialization


In [3]:
x = tf.constant(3, shape=[2,4], dtype="int32") # (element, shape, data_type)
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 3, 3, 3],
       [3, 3, 3, 3]], dtype=int32)>

In [6]:
x = tf.zeros(shape=[2,2], dtype="int32")
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [7]:
x = tf.ones(shape=[3,3], dtype="float32")
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
x = tf.eye(3, dtype="int32")
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [16]:
x = tf.constant([[1,2,3,4],[5,6,7,8]], dtype="int32")
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [18]:
x = tf.random.normal(shape=[3,3], mean=1, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.6842064 ,  0.19772816,  1.7230644 ],
       [ 0.49032313,  0.48984587, -0.2016648 ],
       [ 0.5115762 ,  1.5890971 ,  0.9580268 ]], dtype=float32)>

In [20]:
x = tf.random.uniform(shape=[2,3], minval=0, maxval=1)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09076643, 0.46522832, 0.47482002],
       [0.5342765 , 0.8913988 , 0.19747293]], dtype=float32)>

In [21]:
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

# Mathematical opperations

In [22]:
x = tf.constant([2,3,4])
y = tf.constant([5,6,7])

In [23]:
z = tf.add(x,y)
z_ = x+y

z, z_

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7,  9, 11], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7,  9, 11], dtype=int32)>)

In [25]:
z = tf.subtract(x, y)
z_ = x-y

z, z_

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>)

In [26]:
z = tf.divide(x,y)
z_ = x/y

z, z_

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4       , 0.5       , 0.57142857])>,
 <tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.4       , 0.5       , 0.57142857])>)

In [27]:
z = tf.multiply(x,y)
z_ = x*y

z, z_

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 18, 28], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 18, 28], dtype=int32)>)

In [33]:
z = tf.tensordot(x,y, axes=1)
z_ = tf.tensordot(x,y, axes=0)

z, z_

(<tf.Tensor: shape=(), dtype=int32, numpy=56>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10, 12, 14],
        [15, 18, 21],
        [20, 24, 28]], dtype=int32)>)

# Indexing

In [36]:
x = tf.constant([1,2,3,4,5,6,7,8])

print(x[:])
print(x[1:3])
print(x[::-1])
print(x[::2])


tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)


In [37]:
y = tf.constant([0,3]) # gather multiple index values in one go
z = tf.gather(x, y)

z

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

# Reshaping

In [41]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [42]:
x = tf.reshape(x, (3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [46]:
z = tf.transpose(x, perm=[1,0])
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>